### ISSUE TITLE
AttributeError: 'open3d.open3d.camera.PinholeCameraTrajectory' object has no attribute 'intrinsic'

### ISSUE THREAD

**Issue by Richard-coder** [omiksik/dfusion#1]
My open3d version is 0.6, when I run the main.py, I meet the following problem

```
Traceback (most recent call last):
  File "/home/richard/Desktop/test/dfusion-master/main.py", line 281, in <module>
    IOFVisualiser().visualise(reconstructed_scene, camera_intrinsic_viz, flythough_vis_params)
  File "/home/richard/Desktop/test/dfusion-master/visualiser.py", line 254, in visualise
    traj.intrinsic = O3Dintrinsics
AttributeError: 'open3d.open3d.camera.PinholeCameraTrajectory' object has no attribute 'intrinsic'
```
The origin code is 

```
        traj = PinholeCameraTrajectory()
        traj.intrinsic = O3Dintrinsics
        # print(frames[0])
        # print([fusion.get_stationary_pose(frames[0])])
        traj.extrinsic = Matrix4dVector([fusion.get_stationary_pose(frames[0])])
        ctr = vis.get_view_control()
        ctr.convert_from_pinhole_camera_parameters(traj.intrinsic, traj.extrinsic[0])
```
I make the following change, and the program can run and show render image,

```
        traj = PinholeCameraParameters()
        traj.intrinsic = O3Dintrinsics
        # print(frames[0])
        # print([fusion.get_stationary_pose(frames[0])])
        traj.extrinsic = (Matrix4dVector([fusion.get_stationary_pose(frames[0])]))[0]
        ctr = vis.get_view_control()
        ctr.convert_from_pinhole_camera_parameters(traj)
```

I have never use open3d before, Is my modification correct?

**Comment by Merlinfang** [comment]
Hello, I also meet this error and modified according to your change, but the saved image is very strange, Would like to ask if you have the following warning after changing? Thanks.

`
[ViewControl] ConvertFromPinholeCameraParameters() failed because window height and width do not match.
Rendering frame: 0
`

**Comment by omiksik** [comment]
Hi, thanks for interest! I'll try to get back to this issue later during the week (I think we were using older version of Open3D so there might be some discrepancies in API).

**Comment by AdamAsh2019** [comment]
> My open3d version is 0.6, when I run the main.py, I meet the following problem
> 
> ```
> Traceback (most recent call last):
>   File "/home/richard/Desktop/test/dfusion-master/main.py", line 281, in <module>
>     IOFVisualiser().visualise(reconstructed_scene, camera_intrinsic_viz, flythough_vis_params)
>   File "/home/richard/Desktop/test/dfusion-master/visualiser.py", line 254, in visualise
>     traj.intrinsic = O3Dintrinsics
> AttributeError: 'open3d.open3d.camera.PinholeCameraTrajectory' object has no attribute 'intrinsic'
> ```
> 
> The origin code is
> 
> ```
>         traj = PinholeCameraTrajectory()
>         traj.intrinsic = O3Dintrinsics
>         # print(frames[0])
>         # print([fusion.get_stationary_pose(frames[0])])
>         traj.extrinsic = Matrix4dVector([fusion.get_stationary_pose(frames[0])])
>         ctr = vis.get_view_control()
>         ctr.convert_from_pinhole_camera_parameters(traj.intrinsic, traj.extrinsic[0])
> ```
> 
> I make the following change, and the program can run and show render image,
> 
> ```
>         traj = PinholeCameraParameters()
>         traj.intrinsic = O3Dintrinsics
>         # print(frames[0])
>         # print([fusion.get_stationary_pose(frames[0])])
>         traj.extrinsic = (Matrix4dVector([fusion.get_stationary_pose(frames[0])]))[0]
>         ctr = vis.get_view_control()
>         ctr.convert_from_pinhole_camera_parameters(traj)
> ```
> 
> I have never use open3d before, Is my modification correct?

i have tackled this issue by downgraded the open3d to 0.3 version

**Comment by nowburn** [comment]
@omiksik @AdamAsh2019 
hi, I have also the same problem,  I can run the code by downgraded the open3d to 0.3 version,but the generated images are so bad. so how can I solve the problem?
![reconstruction_rgb_000024](https://user-images.githubusercontent.com/19162375/68861189-fee7a600-0725-11ea-8963-f500adcb17fc.png)

thanks!

**Comment by YuhsiHu** [comment]
Can this project generate a point cloud map of the entire street at the end?

**Comment by YuhsiHu** [comment]
Can this project generate a point cloud map of the entire street at the end?

**Comment by YuhsiHu** [comment]
Can this project generate a point cloud map of the entire street at the end?
